### PR TITLE
Composer updates

### PR DESCRIPTION
**Pull request by rimi-itk**
- Updated "allow-plugins" in composer.json
- Updated Git ignores
- Applied coding standards

### CODE REVIEW

**Review by madsnorgaard — APPROVED** [review]
All changes look good to me.

**Comment by madsnorgaard** [comment]
I am unsure if @agger-magenta is still part of review process but to me this is approved and ready for merge.

**Review by agger-magenta — APPROVED** [review]

**Comment by agger-magenta** [comment]
> I am unsure if @agger-magenta is still part of review process but to me this is approved and ready for merge.

I am not, unfortunately Magenta is no longer in the Drupal business so both I and @mBoegvald are on other projects now.

**Comment by rimi-itk** [comment]
This is an open source project, @agger-magenta, so you are more than welcome to contribute in your spare time.

**Pull request merged**
